// Generated code from Butter Knife. Do not modify!
package com.wisdom.app.fragment;

import android.view.View;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.ViewBinder;

public class MCNL_ShiZhongWuChaFragment$$ViewBinder<T extends com.wisdom.app.fragment.MCNL_ShiZhongWuChaFragment> implements ViewBinder<T> {
  @Override public void bind(final Finder finder, final T target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131297056, "field 'option_u'");
    target.option_u = finder.castView(view, 2131297056, "field 'option_u'");
    view = finder.findRequiredView(source, 2131296524, "field 'tv_show_q'");
    target.tv_show_q = finder.castView(view, 2131296524, "field 'tv_show_q'");
    view = finder.findRequiredView(source, 2131296329, "field 'tv_chooser_i'");
    target.tv_chooser_i = finder.castView(view, 2131296329, "field 'tv_chooser_i'");
    view = finder.findRequiredView(source, 2131296326, "field 'tv_chooser_u'");
    target.tv_chooser_u = finder.castView(view, 2131296326, "field 'tv_chooser_u'");
    view = finder.findRequiredView(source, 2131296562, "field 'tv_dianyayuan'");
    target.tv_dianyayuan = finder.castView(view, 2131296562, "field 'tv_dianyayuan'");
    view = finder.findRequiredView(source, 2131296525, "field 'tv_show_s'");
    target.tv_show_s = finder.castView(view, 2131296525, "field 'tv_show_s'");
    view = finder.findRequiredView(source, 2131296615, "field 'tv_meter1_circle'");
    target.tv_meter1_circle = finder.castView(view, 2131296615, "field 'tv_meter1_circle'");
    view = finder.findRequiredView(source, 2131296331, "field 'tv_jiaodu'");
    target.tv_jiaodu = finder.castView(view, 2131296331, "field 'tv_jiaodu'");
    view = finder.findRequiredView(source, 2131296623, "field 'tv_meter3_circle'");
    target.tv_meter3_circle = finder.castView(view, 2131296623, "field 'tv_meter3_circle'");
    view = finder.findRequiredView(source, 2131296560, "field 'tv_run_time'");
    target.tv_run_time = finder.castView(view, 2131296560, "field 'tv_run_time'");
    view = finder.findRequiredView(source, 2131296632, "field 'tv_meter1_result_clock'");
    target.tv_meter1_result_clock = finder.castView(view, 2131296632, "field 'tv_meter1_result_clock'");
    view = finder.findRequiredView(source, 2131297032, "field 'title'");
    target.title = finder.castView(view, 2131297032, "field 'title'");
    view = finder.findRequiredView(source, 2131297033, "field 'et_celiangshijian'");
    target.et_celiangshijian = finder.castView(view, 2131297033, "field 'et_celiangshijian'");
    view = finder.findRequiredView(source, 2131296636, "field 'tv_meter3_result_clock'");
    target.tv_meter3_result_clock = finder.castView(view, 2131296636, "field 'tv_meter3_result_clock'");
    view = finder.findRequiredView(source, 2131296330, "field 'tv_show_p'");
    target.tv_show_p = finder.castView(view, 2131296330, "field 'tv_show_p'");
    view = finder.findRequiredView(source, 2131296402, "field 'btn_start_test'");
    target.btn_start_test = finder.castView(view, 2131296402, "field 'btn_start_test'");
    view = finder.findRequiredView(source, 2131296617, "field 'tv_meter1_count'");
    target.tv_meter1_count = finder.castView(view, 2131296617, "field 'tv_meter1_count'");
    view = finder.findRequiredView(source, 2131296369, "field 'btn_dianbiao_canshu'");
    target.btn_dianbiao_canshu = finder.castView(view, 2131296369, "field 'btn_dianbiao_canshu'");
    view = finder.findRequiredView(source, 2131296564, "field 'btn_yuan_shuchu'");
    target.btn_yuan_shuchu = finder.castView(view, 2131296564, "field 'btn_yuan_shuchu'");
    view = finder.findRequiredView(source, 2131296405, "field 'et_meter_circle'");
    target.et_meter_circle = finder.castView(view, 2131296405, "field 'et_meter_circle'");
    view = finder.findRequiredView(source, 2131297059, "field 'option_f'");
    target.option_f = finder.castView(view, 2131297059, "field 'option_f'");
    view = finder.findRequiredView(source, 2131296527, "field 'tv_show_pf'");
    target.tv_show_pf = finder.castView(view, 2131296527, "field 'tv_show_pf'");
    view = finder.findRequiredView(source, 2131297030, "field 'bar'");
    target.bar = finder.castView(view, 2131297030, "field 'bar'");
    view = finder.findRequiredView(source, 2131296619, "field 'tv_meter2_circle'");
    target.tv_meter2_circle = finder.castView(view, 2131296619, "field 'tv_meter2_circle'");
    view = finder.findRequiredView(source, 2131297058, "field 'option_p'");
    target.option_p = finder.castView(view, 2131297058, "field 'option_p'");
    view = finder.findRequiredView(source, 2131297022, "field 'tr_3'");
    target.tr_3 = finder.castView(view, 2131297022, "field 'tr_3'");
    view = finder.findRequiredView(source, 2131297057, "field 'option_i'");
    target.option_i = finder.castView(view, 2131297057, "field 'option_i'");
    view = finder.findRequiredView(source, 2131297021, "field 'tr_2'");
    target.tr_2 = finder.castView(view, 2131297021, "field 'tr_2'");
    view = finder.findRequiredView(source, 2131296563, "field 'tv_dianliuyuan'");
    target.tv_dianliuyuan = finder.castView(view, 2131296563, "field 'tv_dianliuyuan'");
    view = finder.findRequiredView(source, 2131296634, "field 'tv_meter2_result_clock'");
    target.tv_meter2_result_clock = finder.castView(view, 2131296634, "field 'tv_meter2_result_clock'");
    view = finder.findRequiredView(source, 2131296377, "field 'et_meter_count'");
    target.et_meter_count = finder.castView(view, 2131296377, "field 'et_meter_count'");
    view = finder.findRequiredView(source, 2131296621, "field 'tv_meter2_count'");
    target.tv_meter2_count = finder.castView(view, 2131296621, "field 'tv_meter2_count'");
    view = finder.findRequiredView(source, 2131296528, "field 'btn_jiaoyan_jieguo'");
    target.btn_jiaoyan_jieguo = finder.castView(view, 2131296528, "field 'btn_jiaoyan_jieguo'");
    view = finder.findRequiredView(source, 2131297061, "field 'btn_set_clock'");
    target.btn_set_clock = finder.castView(view, 2131297061, "field 'btn_set_clock'");
    view = finder.findRequiredView(source, 2131296529, "field 'btn_stop_test'");
    target.btn_stop_test = finder.castView(view, 2131296529, "field 'btn_stop_test'");
    view = finder.findRequiredView(source, 2131296565, "field 'btn_yuan_tingzhi'");
    target.btn_yuan_tingzhi = finder.castView(view, 2131296565, "field 'btn_yuan_tingzhi'");
    view = finder.findRequiredView(source, 2131296526, "field 'tv_chooser_f'");
    target.tv_chooser_f = finder.castView(view, 2131296526, "field 'tv_chooser_f'");
    view = finder.findRequiredView(source, 2131296625, "field 'tv_meter3_count'");
    target.tv_meter3_count = finder.castView(view, 2131296625, "field 'tv_meter3_count'");
  }

  @Override public void unbind(T target) {
    target.option_u = null;
    target.tv_show_q = null;
    target.tv_chooser_i = null;
    target.tv_chooser_u = null;
    target.tv_dianyayuan = null;
    target.tv_show_s = null;
    target.tv_meter1_circle = null;
    target.tv_jiaodu = null;
    target.tv_meter3_circle = null;
    target.tv_run_time = null;
    target.tv_meter1_result_clock = null;
    target.title = null;
    target.et_celiangshijian = null;
    target.tv_meter3_result_clock = null;
    target.tv_show_p = null;
    target.btn_start_test = null;
    target.tv_meter1_count = null;
    target.btn_dianbiao_canshu = null;
    target.btn_yuan_shuchu = null;
    target.et_meter_circle = null;
    target.option_f = null;
    target.tv_show_pf = null;
    target.bar = null;
    target.tv_meter2_circle = null;
    target.option_p = null;
    target.tr_3 = null;
    target.option_i = null;
    target.tr_2 = null;
    target.tv_dianliuyuan = null;
    target.tv_meter2_result_clock = null;
    target.et_meter_count = null;
    target.tv_meter2_count = null;
    target.btn_jiaoyan_jieguo = null;
    target.btn_set_clock = null;
    target.btn_stop_test = null;
    target.btn_yuan_tingzhi = null;
    target.tv_chooser_f = null;
    target.tv_meter3_count = null;
  }
}
