// Generated code from Butter Knife. Do not modify!
package com.wisdom.app.fragment;

import android.view.View;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.ViewBinder;

public class MCNL_QianDongTestFragment$$ViewBinder<T extends com.wisdom.app.fragment.MCNL_QianDongTestFragment> implements ViewBinder<T> {
  @Override public void bind(final Finder finder, final T target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131296369, "field 'btn_dianbiao_canshu'");
    target.btn_dianbiao_canshu = finder.castView(view, 2131296369, "field 'btn_dianbiao_canshu'");
    view = finder.findRequiredView(source, 2131296330, "field 'tv_show_p'");
    target.tv_show_p = finder.castView(view, 2131296330, "field 'tv_show_p'");
    view = finder.findRequiredView(source, 2131296525, "field 'tv_show_s'");
    target.tv_show_s = finder.castView(view, 2131296525, "field 'tv_show_s'");
    view = finder.findRequiredView(source, 2131296627, "field 'et_dianbiaochangshu'");
    target.et_dianbiaochangshu = finder.castView(view, 2131296627, "field 'et_dianbiaochangshu'");
    view = finder.findRequiredView(source, 2131296560, "field 'tv_yunxingshijian'");
    target.tv_yunxingshijian = finder.castView(view, 2131296560, "field 'tv_yunxingshijian'");
    view = finder.findRequiredView(source, 2131296562, "field 'tv_dianyayuan'");
    target.tv_dianyayuan = finder.castView(view, 2131296562, "field 'tv_dianyayuan'");
    view = finder.findRequiredView(source, 2131296391, "field 'sp_qiandongdianliu'");
    target.sp_qiandongdianliu = finder.castView(view, 2131296391, "field 'sp_qiandongdianliu'");
    view = finder.findRequiredView(source, 2131296631, "field 'tv_result3'");
    target.tv_result3 = finder.castView(view, 2131296631, "field 'tv_result3'");
    view = finder.findRequiredView(source, 2131297056, "field 'option_u'");
    target.option_u = finder.castView(view, 2131297056, "field 'option_u'");
    view = finder.findRequiredView(source, 2131296329, "field 'tv_chooser_i'");
    target.tv_chooser_i = finder.castView(view, 2131296329, "field 'tv_chooser_i'");
    view = finder.findRequiredView(source, 2131296630, "field 'tv_result2'");
    target.tv_result2 = finder.castView(view, 2131296630, "field 'tv_result2'");
    view = finder.findRequiredView(source, 2131296565, "field 'btn_yuan_tingzhi'");
    target.btn_yuan_tingzhi = finder.castView(view, 2131296565, "field 'btn_yuan_tingzhi'");
    view = finder.findRequiredView(source, 2131296390, "field 'sp_qiandongdianya'");
    target.sp_qiandongdianya = finder.castView(view, 2131296390, "field 'sp_qiandongdianya'");
    view = finder.findRequiredView(source, 2131296628, "field 'btn_calc_time'");
    target.btn_calc_time = finder.castView(view, 2131296628, "field 'btn_calc_time'");
    view = finder.findRequiredView(source, 2131297029, "field 'title'");
    target.title = finder.castView(view, 2131297029, "field 'title'");
    view = finder.findRequiredView(source, 2131296564, "field 'btn_yuan_shuchu'");
    target.btn_yuan_shuchu = finder.castView(view, 2131296564, "field 'btn_yuan_shuchu'");
    view = finder.findRequiredView(source, 2131297030, "field 'bar'");
    target.bar = finder.castView(view, 2131297030, "field 'bar'");
    view = finder.findRequiredView(source, 2131296527, "field 'tv_show_pf'");
    target.tv_show_pf = finder.castView(view, 2131296527, "field 'tv_show_pf'");
    view = finder.findRequiredView(source, 2131296563, "field 'tv_dianliuyuan'");
    target.tv_dianliuyuan = finder.castView(view, 2131296563, "field 'tv_dianliuyuan'");
    view = finder.findRequiredView(source, 2131297057, "field 'option_i'");
    target.option_i = finder.castView(view, 2131297057, "field 'option_i'");
    view = finder.findRequiredView(source, 2131296326, "field 'tv_chooser_u'");
    target.tv_chooser_u = finder.castView(view, 2131296326, "field 'tv_chooser_u'");
    view = finder.findRequiredView(source, 2131296524, "field 'tv_show_q'");
    target.tv_show_q = finder.castView(view, 2131296524, "field 'tv_show_q'");
    view = finder.findRequiredView(source, 2131296403, "field 'et_qiandongshijian'");
    target.et_qiandongshijian = finder.castView(view, 2131296403, "field 'et_qiandongshijian'");
    view = finder.findRequiredView(source, 2131297059, "field 'option_f'");
    target.option_f = finder.castView(view, 2131297059, "field 'option_f'");
    view = finder.findRequiredView(source, 2131296529, "field 'btn_stop_test'");
    target.btn_stop_test = finder.castView(view, 2131296529, "field 'btn_stop_test'");
    view = finder.findRequiredView(source, 2131296629, "field 'tv_result1'");
    target.tv_result1 = finder.castView(view, 2131296629, "field 'tv_result1'");
    view = finder.findRequiredView(source, 2131297058, "field 'option_p'");
    target.option_p = finder.castView(view, 2131297058, "field 'option_p'");
    view = finder.findRequiredView(source, 2131296402, "field 'btn_start_test'");
    target.btn_start_test = finder.castView(view, 2131296402, "field 'btn_start_test'");
    view = finder.findRequiredView(source, 2131296526, "field 'tv_chooser_f'");
    target.tv_chooser_f = finder.castView(view, 2131296526, "field 'tv_chooser_f'");
    view = finder.findRequiredView(source, 2131296528, "field 'btn_jiaoyan_jieguo'");
    target.btn_jiaoyan_jieguo = finder.castView(view, 2131296528, "field 'btn_jiaoyan_jieguo'");
    view = finder.findRequiredView(source, 2131296331, "field 'tv_jiaodu'");
    target.tv_jiaodu = finder.castView(view, 2131296331, "field 'tv_jiaodu'");
    view = finder.findRequiredView(source, 2131296386, "field 'et_zuidadianliu'");
    target.et_zuidadianliu = finder.castView(view, 2131296386, "field 'et_zuidadianliu'");
  }

  @Override public void unbind(T target) {
    target.btn_dianbiao_canshu = null;
    target.tv_show_p = null;
    target.tv_show_s = null;
    target.et_dianbiaochangshu = null;
    target.tv_yunxingshijian = null;
    target.tv_dianyayuan = null;
    target.sp_qiandongdianliu = null;
    target.tv_result3 = null;
    target.option_u = null;
    target.tv_chooser_i = null;
    target.tv_result2 = null;
    target.btn_yuan_tingzhi = null;
    target.sp_qiandongdianya = null;
    target.btn_calc_time = null;
    target.title = null;
    target.btn_yuan_shuchu = null;
    target.bar = null;
    target.tv_show_pf = null;
    target.tv_dianliuyuan = null;
    target.option_i = null;
    target.tv_chooser_u = null;
    target.tv_show_q = null;
    target.et_qiandongshijian = null;
    target.option_f = null;
    target.btn_stop_test = null;
    target.tv_result1 = null;
    target.option_p = null;
    target.btn_start_test = null;
    target.tv_chooser_f = null;
    target.btn_jiaoyan_jieguo = null;
    target.tv_jiaodu = null;
    target.et_zuidadianliu = null;
  }
}
